### ISSUE TITLE
Barcode Shiny App

### ISSUE THREAD

**Issue by gringer** [kinow/nz-shiny-server#17]
Hi, to get myself acquainted with this server, I'd like to submit a [code 128B] barcode generator App to this Shiny server. I have the following stumbling blocks:

* My code has *no* dependencies; it works off base R + shiny (I'm not sure if I can delete the entire "install R packages" block)
* My code is hosted on gitlab, and I'm not sure how to create a pull request across sites

This is what I think the .yml should look like:

```
# check out code
- git:
    repo: 'https://gitlab.com/gringer/barcoder.git'
    dest: /srv/shiny-server/barcoder
    version: d55c5e73185b9f43ed42557ded3aff0c69b99234
# permissions
- file:
    path: /srv/shiny-server/barcoder
    state: directory
    mode: 0750
    owner: shiny
    group: shiny
```
